name: Build and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools

    # Step 4: Extract version from setup.py
    - name: Extract package version
      id: extract_version
      run: |
        python -c "
import runpy
setup_cfg = runpy.run_path('setup.py')
version = setup_cfg.get('version', 'unknown')
print(f'::set-output name=version::{version}')
        "

    # Step 5: Build the Python project
    - name: Build the project
      run: python -m build

    # Step 6: Create Release
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: dist/*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ steps.extract_version.outputs.version }}
        name: Release v${{ steps.extract_version.outputs.version }}
        body: |
          Automatically generated release for commit: ${{ github.sha }}
